- postgreSQL_setup.md
- src/main/java/infrastructure/CustomerListingResources.java
- src/main/java/infrastructure/dto/in/profile/GetCustomerListingsDto.java
- src/main/java/infrastructure/dto/in/profile/GetCustomerPostedListingsDto.java
- src/main/java/infrastructure/dto/out/listing/StarredListingPageDto.java
- This is add get all my starred listings by passing in a customer profile Id.
- Pass local unit tests
- Test locally using postman 
- Test remotely in aws server. 
> Be 19: Add endpoint to get all my starred listings

- .github/workflows/cicd.yml
- deploy_script.sh
- Add CI/CD for using github actions with aws ec2
- This will need to be tested after the merge as main is the default branch 
> BE-39: Add CI/CD for main branch

- src/test/java/infrastructure/ListingResourcesIT.java
- Added integration tests for get-listing under conditions when listing exists and does not exist. 
> BE-25: Added integration tests for get-listing

- src/main/java/domain/listing/ListingRepository.java
- src/main/java/domain/listing/ListingService.java
- src/main/java/domain/profile/CustomerProfileRepository.java
- src/main/java/domain/profile/CustomerProfileService.java
- src/main/java/domain/profile/UpdateCustomerProfile.java
- src/main/java/infrastructure/CustomerProfileResources.java
- src/main/java/infrastructure/ListingResources.java
- src/main/java/infrastructure/dto/in/profile/UpdateCustomerProfileDto.java
- src/main/java/infrastructure/result/UpdateCustomerProfileResult.java
- src/main/java/infrastructure/result/UpdateListingResult.java
- src/main/java/infrastructure/sql/PanacheCustomerProfileRepository.java
- src/main/java/infrastructure/sql/PanacheListingRepository.java
- src/main/java/infrastructure/sql/entity/CustomerProfileEntity.java
- src/main/java/infrastructure/sql/entity/ListingEntity.java
- src/test/java/domain/listing/ListingServiceTest.java
- This ticket fixed the update listing and update profile issue.
- Tested locally, now unit test passes
> BE-41: fix the issue for update listing and update profile

- src/test/java/infrastructure/ListingResourcesIT.java
- This is to fix the tear down issue for create listing IT
- Running locally and check in DB
> BE-43: fix the IT issue

- src/test/java/infrastructure/ListingResourcesIT.java
-Added IT for update-listing, get-listing and delete-listing, one typo was found in the previous tests branch such that three IT are being updated together in this branch
> BE-27: Added IT for update-listing, get-listing and delete-listing

- src/test/java/infrastructure/CustomerProfileResourcesIT.java
- src/test/java/infrastructure/ListingResourcesIT.java
- Add IT for create customer profile
- Pass local integration test for create customer profile
closes #47
> BE-33: add IT for create customer profile

- src/test/java/infrastructure/CustomerProfileResourcesIT.java
- src/test/java/infrastructure/ListingResourcesIT.java
- Add integration tests for get customer profile
- Pass and affect existing tests
> Be 34: Add integration tests for get customer profile

- src/main/java/domain/listing/ListingService.java
- src/main/java/domain/profile/CustomerProfileService.java
- src/main/java/infrastructure/CustomerListingResources.java
- src/main/java/infrastructure/result/CustomerStarListingResult.java
- src/main/java/infrastructure/result/ListingStarListingResult.java
- src/test/java/domain/listing/ListingServiceTest.java
- src/test/java/infrastructure/CustomerProfileResourcesIT.java
- Updated the error message based on exceptions happened to star listing endpoint
- Pass existing unit and integration tests
- Test locally in postman
> Be 45: Update error message for star listing page exception

- src/main/java/domain/profile/CustomerProfileService.java
- src/test/java/infrastructure/CustomerProfileResourcesIT.java
- This ticket is to add IT for update customer profile
- Tested several scenarios for update customer profile
> BE-35: add IT for update customer profile

- src/main/java/domain/profile/CustomerProfileService.java
- src/test/java/infrastructure/CustomerProfileResourcesIT.java
- Added IT for deleting customer profile endpoint.
- Passed several testing scenarios: 
- When customer does not exist, returns message indicating that
- Do not delete when customer has created listings.
- Does delete when they do not have listings.
> Be 36: Add IT for delete customer profile endpoint

- src/test/java/infrastructure/CustomerListingResourcesIT.java
- src/test/java/infrastructure/ListingResourcesIT.java
- Added IT for starlisting, modified with BE-45, and added IT for getCustomerPostedListings. A bug was found when the listing ID is invalid and customterID exists, and a wrong message will return. This IT is passed with the modification of BE-45
> BE-28: Added IT for starlisting, modified with BE-45, and added IT for getCustomerPostedListings

- src/test/java/infrastructure/CustomerListingResourcesIT.java
- src/test/java/infrastructure/ListingResourcesIT.java
- Added IT for getStarredListings
> BE-30: Added IT for getStarredListings

- src/test/java/infrastructure/CustomerListingResourcesIT.java
- src/test/java/infrastructure/ListingResourcesIT.java
- Added IT for getListingByPage
> BE-31: Added IT for getListingByPage

- src/test/java/infrastructure/CustomerListingResourcesIT.java
- src/test/java/infrastructure/ListingResourcesIT.java
- Added IT for GetListingWithCustomerDetails, finished IT for CustomerListingResources. As a constraint was set that when a customer has listing posted, their profile can not be deleted.In this case, there won't be situation where a customerId is not valid.
> BE-32: Added IT for GetListingWithCustomerDetails, finished IT for CustomerListingResources.

- src/main/java/domain/listing/ListingService.java
- src/main/java/domain/profile/CustomerProfileService.java
- src/main/java/infrastructure/CustomerListingResources.java
- src/main/java/infrastructure/result/CustomerStarResult.java
- src/main/java/infrastructure/result/CustomerUnStarResult.java
- src/main/java/infrastructure/result/ListingStarResult.java
- src/main/java/infrastructure/result/ListingUnStarResult.java
- src/main/java/infrastructure/sql/PanacheListingRepository.java
- src/test/java/domain/listing/ListingServiceTest.java
- src/test/java/infrastructure/CustomerListingResourcesIT.java
- src/test/java/infrastructure/CustomerListingResourcesMockIT.java
- Added unstar endpoint so that customers could unstar a listing after they've starred it
- Pass existing unit tests and ITs
> Be 44: Add unstar endpoint

- src/main/java/domain/profile/CreateCustomerProfile.java
- src/main/java/domain/profile/CustomerProfileService.java
- src/test/java/domain/profile/CustomerProfileServiceTest.java
- src/test/java/infrastructure/CustomerListingResourcesIT.java
- src/test/java/infrastructure/CustomerProfileResourcesIT.java
- Added CustomerProfileServiceTest
> BE-23: Added IT for CustomerProfileService

- src/main/java/domain/profile/CustomerProfileService.java
- src/main/java/domain/profile/Login.java
- src/main/java/infrastructure/CustomerProfileResources.java
- src/main/java/infrastructure/dto/in/profile/LoginDto.java
- src/main/java/infrastructure/sql/PanacheCustomerProfileRepository.java
- Add login endpoint, it needs to be called with corresponding email and password.
- Passed local postman test, IT to be added
> BE-46: Add login endpoint

- src/test/java/domain/profile/CustomerProfileServiceTest.java
Add integration test for login endpoint
> BE 47 Add integration test for login endpoint

- src/main/java/infrastructure/sql/PanacheCustomerProfileRepository.java
- Fix the bug for update customer profile endpoint. Avatar should be updated
- Test locally and in develop environment.
- Test in aws server
> BE-48: fix the bug to update avatar for customer

- src/main/java/domain/profile/CustomerProfileService.java
- src/main/java/infrastructure/CustomerProfileResources.java
- src/main/java/infrastructure/dto/in/profile/CheckEmailDto.java
- Add the endpoint to check customer by email
- If email is occupied, then return customer
- Else return error with code: 4001 
- Test locally and in postman
- Deploy to server and test for existing customers
closes #98
> BE-49: add check email endpoint

- src/main/java/domain/listing/ListingRepository.java
- src/main/java/domain/listing/ListingService.java
- src/main/java/domain/listing/SearchListing.java
- src/main/java/infrastructure/ListingResources.java
- src/main/java/infrastructure/dto/in/listing/SearchListingDto.java
- src/main/java/infrastructure/sql/PanacheListingRepository.java
- Add endpoint to get listings by title.
- Test locally and in postman
- Merge the changes into server and test with existing listings.
> BE-50: add endpoint to get listing by title

- src/test/java/domain/profile/CustomerProfileServiceTest.java
- Added unit test and integration test for check email endpoint
> Be-51: Added unit test and integration test for check email endpoint

- src/main/java/infrastructure/ListingResources.java
- src/test/java/domain/listing/ListingServiceTest.java
- src/test/java/infrastructure/ListingResourcesIT.java
-  Added unit tests for searchListing and IT for searchListing endpoint. All tests passed successfully.
> BE-52: Added unit tests for searchListing and IT for searchListing endpoint

- src/test/java/domain/listing/ListingServiceTest.java
- Make the line coverage of ListingService reaches 100%
> BE-54: Make the line coverage of ListingService reaches 100%

- src/test/java/domain/profile/CustomerProfileServiceTest.java
- Modified CustomerLogin tests to fully cover all lines 
> BE-55: Completed the CustomerProfileServices to fully cover all lines

- src/test/java/domain/listing/ListingServiceTest.java
- This PR is to fix the test cases in `main` branch
- Running mvn clean install locally. 
- No
> BE-57: fix test cases

- src/test/java/infrastructure/CustomerListingResourcesIT.java
- Add integration tests for get completed listings for a customer
> BE-56: Add integration tests for get completed listings for a customer

- src/main/java/infrastructure/CustomerProfileResources.java
- src/main/java/infrastructure/dto/out/profile/CustomerProfileDetailsInternalDto.java
- src/test/java/infrastructure/CustomerProfileResourcesIT.java
- This endpoint is used for customer profile by FE
- Test in postman with local database
#closes #118
> BE-61: add endpoint to get full customer details for internal use

- src/main/java/infrastructure/CustomerListingResources.java
- src/test/java/infrastructure/CustomerListingResourcesIT.java
- src/test/java/infrastructure/CustomerListingResourcesMockIT.java
- Added untested cases in CustomerListingResources
> BE-58: Add IT for CustomerListingResources

- src/main/java/domain/profile/CustomerProfileService.java
- src/main/java/infrastructure/CustomerProfileResources.java
- src/main/java/infrastructure/result/RequireUserResult.java
- src/main/java/infrastructure/result/UpdateCustomerProfileResult.java
- src/main/java/infrastructure/result/UpdateListingResult.java
- src/test/java/domain/profile/CustomerProfileServiceTest.java
- src/test/java/infrastructure/CustomerProfileResourcesIT.java
- Fixed bug when updating profile with invalid ID, will return the wrong message. Modified the tests for requireUser and customerLogin
> BE-59: Fixed bug when update profile with invalid ID, will return wrong message

- src/test/java/infrastructure/CustomerProfileResourcesIT.java
> BE-62: Add IT for CustomerProfileResources
